name = "craftoria-2"
author = "TeamAOE"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a16d86ecd72dc565d75c4d64f2a376ab8c92a6b6a3c03c6b67daf6a30fcbb312"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.97"
