name = "craftoria-2"
author = "TeamAOE"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb73d80426723497dfb92e7c1ab370aca5ab63a9bb6ad0423ee0aafc3e650916"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.60-beta"
